### ISSUE TITLE
Provide vignette on aggregating uncertainty

### ISSUE THREAD

**Issue by bgctw** [bgctw/REddyProc#23]
There are continuous support request on how to aggregate the uncertainty to daily and annual aggregates. Would be good to provide an example with the package.

**Comment by lsigut** [comment]
I have already done that as a part of my Summary workflow that I plan to share very soon. We could link it here once I put it on GitHub. Any comments welcome of course.

**Comment by lsigut** [comment]
The complete example including uncertainty aggregation is available here:
[https://github.com/lsigut/EC_workflow](https://github.com/lsigut/EC_workflow)
The relevant part is inside `siteyear_Summary_2018-09-17.R`.

**Comment by bgctw** [comment]
Dear Ladislav,

As I see you aggregate uncertainty with neglecting correlations, i.e. assuming independent measurements.
To my experience, this will in many cases underestimate uncertainty in annual aggregates quite a lot.

Yours
Thomas

**Comment by lsigut** [comment]
Thank you for the feedback! I was actually surprised that indeed the resulting uncertainties were quite low. I used rather simplistic approach, aggregating "in quadrature" mostly based on the Section Uncertainty Quantification in book Aubinet et al., 2012. Do you know about some reference for uncertainty aggregation including correlations?

**Comment by bgctw** [comment]
I created a vignette in #25.
The markdown version is also in the repo and can be [directly displayed](https://github.com/bgctw/REddyProc/blob/uncertaintyRmd/vignettes/aggUncertainty.md).
@lsigut What is your opinion?

**Comment by bgctw** [comment]
Markdown version of the vignette now in linked from [master bruch](https://github.com/bgctw/REddyProc/blob/master/vignettes/aggUncertainty.md)

**Comment by lsigut** [comment]
> I created a vignette in #25.
> The markdown version is also in the repo and can be [directly displayed](https://github.com/bgctw/REddyProc/blob/uncertaintyRmd/vignettes/aggUncertainty.md).
> @lsigut What is your opinion?

This looks great Thomas. Thank you for explanations and nice demonstration. I will use it for my work and will implement it in the Summary EC workflow. I omitted correlations but also 1.96 stdDev.
