### ISSUE TITLE
about footprint modeling

### ISSUE THREAD

**Issue by zhengjiji456** [bgctw/REddyProc#52]
Hi,

REddyProc is a great package. I wonder whether this package would realize the function of footprint modeling in Tovi in the future?

Thanks

**Comment by lsigut** [comment]
Dear @zhengjiji456,
to my knowledge, what is currently used in Tovi is 2D footprint modelling, specification of target area (or region of interest; can be more than one) and data filtering with the requirement of X% overlap. What is currently available in [openeddy](https://github.com/lsigut/openeddy) is filtering against region of interest boundary using 1D footprint model (reported as distance from tower; EddyPro software output). It is explained in ROI boundary section of [EC workflow](https://github.com/lsigut/EC_workflow). It is my long-term plan for openeddy to include also filtering comparable to Tovi.

**Comment by zhengjiji456** [comment]
> Dear @zhengjiji456,
> to my knowledge, what is currently used in Tovi is 2D footprint modelling, specification of target area (or region of interest; can be more than one) and data filtering with the requirement of X% overlap. What is currently available in [openeddy](https://github.com/lsigut/openeddy) is filtering against region of interest boundary using 1D footprint model (reported as distance from tower; EddyPro software output). It is explained in ROI boundary section of [EC workflow](https://github.com/lsigut/EC_workflow). It is my long-term plan for openeddy to include also filtering comparable to Tovi.

Thanks for sharing this package
